name: Test Build Morphe Patches

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android Patches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Build Morphe Patches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :patches:buildAndroid generatePatchesList

      - name: Upload MPP Patch Bundle
        uses: actions/upload-artifact@v4
        with:
          name: morphe-patch-bundle
          path: |
            **/build/libs/*.mpp
            **/patches-bundle.json
            **/patches-list.json
